version: '3.9'

services:
  app:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./:/user/src/app/data
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
